logging:
  level:
    root: INFO
    com.uex.trading: DEBUG
    io.netty: INFO
    org.redisson: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ultra-trading.log
    max-size: 100MB
    max-history: 30
